### ISSUE TITLE
Can't add gnubatch-feeder service

### ISSUE THREAD

**Issue by nigelhorne** [ccin2p3/puppet-etc_services#2]
'gnubatch-feeder/tcp':
      port => '48105',
      comment => 'Feeder port for GNUbatch Connection';

Gives:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: validate_re(): "gnubatch-feeder/tcp" does not match "^\\w+/(tcp|udp)$" at /export/home/puppet/manifests/gnubatchtest.pp:66 on node gnubatchtest.be-md.ncbi.nlm.nih.gov
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by nigelhorne** [comment]
I am assuming that changing the regex to this would fix it:

validate_re($name, '^(\w|-)+/(tcp|udp)$')

**Comment by nigelhorne** [comment]
Though the service probably doesn't want to start or end with a dash...

**Comment by amogh1986** [comment]
I guess this would help:

  validate_re($name, '^\w+(?:-\w+)+/(tcp|udp)$')

**Comment by riton** [comment]
Fixed by #4 .
