### ISSUE TITLE
Please release 1.0.1.

### ISSUE THREAD

**Issue by crayfishx** [ccin2p3/puppet-etc_services#5]
Hi, 

We need 2e24f7ecbbce2fbc6ec337f4716392944088582b for our implementation currently... could you please release a 1.0.1 containing this fix?

Many thanks

**Comment by riton** [comment]
We'll sure do !

**Comment by riton** [comment]
@crayfishx  Thanks for your reminder, this release should have been done a while ago ...

We have released `v1.0.2` and this is available [here](https://forge.puppetlabs.com/ccin2p3/etc_services/1.0.2/changelog).

Feel free to create Pull Requests if you find something that could be improved or changed to fit your needs.
