### ISSUE TITLE
1.1.0 forge release file permissions

### ISSUE THREAD

**Issue by alexjfisher** [ccin2p3/puppet-etc_services#7]
I've just upgraded from 1.0.2 to 1.1.0, but now catalog compilation fails as my puppetserver can't read the module's files.
eg
```
Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Failed to generate additional resources using 'eval_generate': Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/dev/modules/etc_services/metadata.json
Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Could not evaluate: Could not retrieve file metadata for puppet:///pluginfacts: Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/dev/modules/etc_services/metadata.json
```
Compared to 1.0.2 (and all other modules in my environment), there is no world read permission set on any of the 1.1.0 files.

Can this be fixed?

Thanks

**Comment by riton** [comment]
Release `v1.1.1` fixes this issue. Sorry for the inconvenience.

**Comment by alexjfisher** [comment]
@riton Thanks!  I've lost count how many times a non standard umask has bitten me! :)
